#!/usr/bin/env node
// Regenerates ../fr-words.js from public word lists.
//
//   node build-words.mjs [common-cutoff] [accepted-cutoff]
//
// Dictionary = an-array-of-french-words (every inflected form, from the
// Grammalecte lexicon) intersected with OpenSubtitles word frequencies, minus
// the LDNOOBW French blocklist. Two tiers:
//   FR_COMMON — top N (default 50000) frequency: the puzzle's "official" list,
//               used for the word total, ranks and the answer reveal.
//   FR_EXTRA  — the rest down to the accepted cutoff (default 400000): real but
//               rarer words, still accepted and scored as bonus words.
// Only words a honeycomb could ever hold are kept: 4+ letters, no hyphen or
// apostrophe, at most 7 distinct letters once accents are stripped.

const COMMON = Number(process.argv[2] || 50000);
const ACCEPTED = Number(process.argv[3] || 400000);

const SOURCES = {
  dict: 'https://cdn.jsdelivr.net/npm/an-array-of-french-words/index.json',
  freq: 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/fr/fr_full.txt',
  blocklist: 'https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/fr',
};

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.text();
}

const [dictRaw, freqRaw, blockRaw] = await Promise.all(Object.values(SOURCES).map(fetchText));

const strip = (w) => w.normalize('NFD').replace(/[̀-ͯ]/g, '')
  .replace(/œ/g, 'oe').replace(/æ/g, 'ae');
const playable = (w) => /^[a-zà-ÿœæ]{4,}$/.test(w) && new Set(strip(w)).size <= 7;

const rank = new Map();
freqRaw.split('\n', ACCEPTED).forEach((line, i) => {
  const w = line.split(' ')[0];
  if (w && !rank.has(w)) rank.set(w, i);
});

const blocked = new Set(blockRaw.split('\n').map((w) => strip(w.trim().toLowerCase())).filter(Boolean));

const common = [], extra = [];
for (const w of JSON.parse(dictRaw)) {
  if (!playable(w) || !rank.has(w) || blocked.has(strip(w))) continue;
  (rank.get(w) < COMMON ? common : extra).push(w);
}
common.sort(); extra.sort();

const out =
  `// Generated by tools/build-words.mjs — do not edit by hand.\n` +
  `// French lexicon ∩ subtitle frequency, minus blocklist.\n` +
  `// FR_COMMON: top-${COMMON} (${common.length} words). FR_EXTRA: to top-${ACCEPTED} (${extra.length} words).\n` +
  `const FR_COMMON = ${JSON.stringify(common.join(' '))};\n` +
  `const FR_EXTRA = ${JSON.stringify(extra.join(' '))};\n`;

const { writeFileSync } = await import('node:fs');
const { fileURLToPath } = await import('node:url');
const dest = fileURLToPath(new URL('../fr-words.js', import.meta.url));
writeFileSync(dest, out);
console.log(`Wrote ${dest}: ${common.length} common + ${extra.length} extra, ${(out.length / 1024).toFixed(0)}KB`);
