// Scattergories category pool — family friendly, deliberately broad so a
// 12-category sheet rarely repeats. Order matters: the daily puzzle picks by
// seeded index, so INSERTING or REORDERING entries changes past puzzles.
// Append new categories at the end.
'use strict';

const SCAT_CATEGORIES = [
  'Boy’s name',
  'Girl’s name',
  'Animals',
  'Things in a kitchen',
  'Countries',
  'Cities',
  'Foods',
  'Things that are cold',
  'Sports',
  'Colours',
  'School subjects',
  'Things in the sky',
  'Musical instruments',
  'Things you wear',
  'Types of drink',
  'Jobs',
  'Board games',
  'Things in a garden',
  'Cartoon characters',
  'Fruits',
  'Vegetables',
  'Things with wheels',
  'Things in a hospital',
  'Reasons to be late',
  'Things at the beach',
  'Movie titles',
  'Song titles',
  'TV shows',
  'Book titles',
  'Authors',
  'Things in a fridge',
  'Breakfast foods',
  'Desserts',
  'Things that are round',
  'Things that fly',
  'Things in the ocean',
  'Birds',
  'Insects',
  'Trees',
  'Flowers',
  'Things in a toolbox',
  'Things in a classroom',
  'Things you recycle',
  'Board game pieces',
  'Card games',
  'Video games',
  'Things in a backpack',
  'Things you find in a purse',
  'Things in the bathroom',
  'Types of weather',
  'Things that are sticky',
  'Things that are loud',
  'Things that smell good',
  'Things that are soft',
  'Things that are heavy',
  'Something you shout',
  'Excuses',
  'Bad habits',
  'Hobbies',
  'Things you collect',
  'Things you do at a party',
  'Holiday traditions',
  'Things at a birthday party',
  'Things in a first aid kit',
  'Camping gear',
  'Things in a car',
  'Road trip games',
  'Modes of transport',
  'Airlines',
  'Things at an airport',
  'Souvenirs',
  'Islands',
  'Rivers',
  'Mountains',
  'Lakes',
  'Canadian things',
  'Provinces or states',
  'Capital cities',
  'Languages',
  'Currencies',
  'Historical figures',
  'Inventors',
  'Scientists',
  'Explorers',
  'Athletes',
  'Hockey teams',
  'Sports equipment',
  'Olympic events',
  'Things on a farm',
  'Baby animals',
  'Animals with tails',
  'Things that hop',
  'Pets',
  'Dog breeds',
  'Things in a zoo',
  'Dinosaurs',
  'Mythical creatures',
  'Superheroes',
  'Villains',
  'Magic spells',
  'Fairy tale characters',
  'Nursery rhymes',
  'Things in a castle',
  'Pirate things',
  'Space things',
  'Planets or moons',
  'Constellations',
  'Things in a lab',
  'Elements',
  'Body parts',
  'Things a doctor says',
  'Medicines',
  'Types of exercise',
  'Yoga poses',
  'Dance styles',
  'Music genres',
  'Bands',
  'Singers',
  'Things in an orchestra',
  'Things at a concert',
  'Types of shoes',
  'Types of hats',
  'Jewellery',
  'Fabrics',
  'Things in a closet',
  'Laundry things',
  'Cleaning supplies',
  'Things in a junk drawer',
  'Things in a garage',
  'Power tools',
  'Building materials',
  'Rooms in a house',
  'Furniture',
  'Things on a desk',
  'Office supplies',
  'Computer things',
  'Apps or websites',
  'Things you plug in',
  'Kitchen appliances',
  'Cooking verbs',
  'Spices or herbs',
  'Sauces',
  'Cheeses',
  'Types of bread',
  'Pasta shapes',
  'Pizza toppings',
  'Sandwich fillings',
  'Soups',
  'Salad ingredients',
  'Candy',
  'Ice cream flavours',
  'Baking ingredients',
  'Things in a lunchbox',
  'Snack foods',
  'Junk food',
  'Healthy foods',
  'Things that are spicy',
  'Things that are sour',
  'Restaurant chains',
  'Things on a menu',
  'Grocery store items',
  'Store names',
  'Brand names',
  'Things you buy online',
  'Things that cost a lot',
  'Things that are free',
  'Ways to earn money',
  'Things in a wallet',
  'Bank things',
  'Things in the news',
  'Magazines or newspapers',
  'Board room words',
  'Things a teacher says',
  'Things in a library',
  'Types of stories',
  'Poems or poets',
  'Shakespeare things',
  'Words in a dictionary',
  'Punctuation or grammar terms',
  'Math terms',
  'Shapes',
  'Units of measurement',
  'Things you count',
  'Things that come in pairs',
  'Things in a deck of cards',
  'Dice games',
  'Puzzle types',
  'Riddles',
  'Things that are square',
  'Things that spin',
  'Things that float',
  'Things that melt',
  'Things that grow',
  'Things that shine',
  'Things that stretch',
  'Things that break easily',
  'Things you sit on',
  'Things you climb',
  'Things you throw',
  'Things you squeeze',
  'Things you fold',
  'Things you open',
  'Things with buttons',
  'Things with strings',
  'Things with a screen',
  'Things with holes',
  'Things you sharpen',
  'Things that come in a box',
  'Things in a bag of chips',
  'Things that are green',
  'Things that are red',
  'Things that are blue',
  'Things that are yellow',
  'Things that are black and white',
  'Things you see at night',
  'Things you do in the morning',
  'Bedtime things',
  'Things you dream about',
  'Ways to relax',
  'Things that wake you up',
  'Alarm sounds',
  'Types of noises',
  'Animal sounds',
  'Things that echo',
  'Things you whisper',
  'Ways to say hello',
  'Ways to say goodbye',
  'Compliments',
  'Feelings',
  'Personality traits',
  'Things that make you laugh',
  'Things that scare you',
  'Fears or phobias',
  'Things that are lucky',
  'Superstitions',
  'Wishes',
  'Goals',
  'New year resolutions',
  'Rules at home',
  'Chores',
  'Family members',
  'Things grandparents say',
  'Baby things',
  'Playground things',
  'Toys',
  'Things in a toy box',
  'Lego creations',
  'Craft supplies',
  'Things you draw',
  'Art materials',
  'Famous paintings or artists',
  'Museums',
  'Things in a photo',
  'Costumes',
  'Halloween things',
  'Christmas things',
  'Birthday gifts',
  'Wedding things',
  'Things at a picnic',
  'Barbecue things',
  'Summer things',
  'Winter things',
  'Spring things',
  'Autumn things',
  'Things that are seasonal',
  'Things at a fair',
  'Amusement park rides',
  'Circus things',
  'Things in a parade',
  'Things at a sports game',
  'Things in a stadium',
  'Team names',
  'Trophies or awards',
  'Ways to win',
  'Things you shout at a game',
  'Referee calls',
  'Things in a gym',
  'Swimming things',
  'Winter sports',
  'Water sports',
  'Things on a bike',
  'Things in a boat',
  'Fishing things',
  'Hiking gear',
  'Things in a tent',
  'Survival items',
  'Emergency things',
  'Things in a storm',
  'Natural disasters',
  'Things that are hot',
  'Things in a desert',
  'Things in a jungle',
  'Things in a forest',
  'Things underground',
  'Rocks or minerals',
  'Things in a cave',
  'Types of maps',
  'Directions',
  'Street names',
  'Things on a street',
  'Buildings',
  'Bridges or landmarks',
  'Places to visit',
  'Vacation activities',
  'Things in a hotel',
  'Things you pack',
  'Things you forget',
  'Things you lose',
  'Things you find',
  'Things in a lost and found',
];
