#!/usr/bin/env node
// Regenerates ../words.js from public word lists.
//
//   node build-words.mjs [frequency-cutoff]
//
// Dictionary = ENABLE1 (valid word-game words, public domain) intersected
// with the top N entries of Norvig's Google-corpus frequency list, minus the
// LDNOOBW blocklist. Raise the cutoff (default 100000) if playtesting shows
// too many real words rejected; lower it if obscure words annoy players.

const CUTOFF = Number(process.argv[2] || 100000);

const SOURCES = {
  enable: 'https://www.norvig.com/ngrams/enable1.txt',
  freq: 'https://www.norvig.com/ngrams/count_1w.txt',
  blocklist: 'https://raw.githubusercontent.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words/master/en',
};

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  return res.text();
}

const [enableRaw, freqRaw, blockRaw] = await Promise.all(
  Object.values(SOURCES).map(fetchText)
);

const isPlayable = (w) => /^[a-z]{3,17}$/.test(w);

const common = new Set(
  freqRaw
    .split('\n', CUTOFF)
    .map((line) => line.split('\t')[0])
);

const blocklist = new Set(
  blockRaw.split('\n').map((w) => w.trim().toLowerCase()).filter(isPlayable)
);

const words = enableRaw
  .split('\n')
  .map((w) => w.trim().toLowerCase())
  .filter((w) => isPlayable(w) && common.has(w) && !blocklist.has(w))
  .sort();

const header =
  `// Generated by tools/build-words.mjs — do not edit by hand.\n` +
  `// ENABLE1 ∩ top-${CUTOFF} frequency, minus blocklist. ${words.length} words.\n`;

const out =
  header +
  `const BOGGLE_WORDS = ${JSON.stringify(words.join(' '))};\n` +
  `const BOGGLE_BLOCKLIST = ${JSON.stringify([...blocklist].sort().join(' '))};\n`;

const { writeFileSync } = await import('node:fs');
const { fileURLToPath } = await import('node:url');
const dest = fileURLToPath(new URL('../words.js', import.meta.url));
writeFileSync(dest, out);
console.log(`Wrote ${dest}: ${words.length} words, ${blocklist.size} blocked, ${(out.length / 1024).toFixed(0)}KB`);
